[project]
name = "repl-nix-streamlitopenaichatbot"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "openai>=1.57.3",
    "streamlit>=1.41.0",
]
